### ISSUE TITLE
Debugger tracking issue - Start here if you're having issues with the debugger

### ISSUE THREAD

**Issue by ewanharris** [appcelerator/vscode-appcelerator-titanium#117]
To keep the PR free for review comments, please use this issue to report any issues and ask question about the upcoming debugger.

Please see the #116 for instructions as to how to use the debugger before release.

**Comment by raybelisle** [comment]
Everything is installed as per the instructions. If I run ios-webkit-debug-proxy from the command line, it launches properly but if I try and run from the Debug by clicking the green play button, I get the following error: Unable to find ios-webkit-debug-proxy. Please ensure it is installed

Kinda stuck :)

**Comment by ewanharris** [comment]
Erugh, silly error on my part sorry!. Left some debugging in from when I was testing that check, I've just updated the build [here](https://github.com/ewanharris/vscode-appcelerator-titanium/releases/tag/debugger-prerelease) to fix that.

**Comment by ewanharris** [comment]
We just released 0.5.0 with debugging, I'm going to repurpose this issue into a "support" issue while people update and (hopefully!) check it out.

**Comment by ewanharris** [comment]
One thing to note, currently there is a known issue with iOS 13, see https://github.com/google/ios-webkit-debug-proxy/pull/317. We're tracking that issue and hopefully it will be resolved soon

**Comment by ewanharris** [comment]
Closing out as this has served it's purpose
