### ISSUE TITLE
Debugger does not stop at widget lib js file

### ISSUE THREAD

**Issue by developer82** [appcelerator/vscode-appcelerator-titanium#140]
### Description
I have read this guide - https://devblog.axway.com/mobile-apps/vs-code-debugging-for-titanium/ - about setting up the debugger with Visual Studio Code. It works!
But, what I wish to do is to debug a Widget that I'm developing. When I set a breakpoint inside a js file inside the lib folder in the widget it appears as a round empty gray circle with tooltip saying "Unverified breakpoint" and it does not break. A breakpoint in the widget itself does work.

As a workaround I can break inside the widget and then "step into" the instance I'm making of the class in the lib folder.

### Steps to reproduce the Bug
Steps to reproduce the behavior, e.g.:
1. Create a Widget
2. Create a js file with a class and function to that class inside the lib folder
3. Set breakpoint in the function code.
4. In Widget code create an instance of the class and call the function.
5. Run debugger.

### Expected Behavior
The debugger should break at breakpoint.

**Comment by ewanharris** [comment]
0.12.2 was just released with this fix, it should be rolling out shortly
