### ISSUE TITLE
VS code complains Project 'ABC' is missing required library: 'lib/titanium.jar'

### ISSUE THREAD

**Issue by jason919** [appcelerator/vscode-appcelerator-titanium#152]
updated to new VS code titanium extension, now I am getting this message:

Project 'ABC' is missing required library: 'lib/titanium.jar'.  There is nothing wrong my android sdk. since everything works fine with Atom (with Appcelerator extension).

**Comment by ewanharris** [comment]
@jason919 are you getting that error during a build of your application? I can't find any context for that error in our CLI build. Could you please provide a more complete log for us to help diagnose the issue?

**Comment by jason919** [comment]
it is not during the build, just when I open the project in VS code, the "problem" pane shows that error.

**Comment by ewanharris** [comment]
@jason919 Interesting, to my knowledge this extension will not be adding that to the Problem pane. I believe that the problem pane _should_ state what extension is adding that warning, does it definitely point to this extension providing the warning?

**Comment by ewanharris** [comment]
@jason919, did you track down where that warning was coming from?

**Comment by jason919** [comment]
Somehow it magically disappeared. I can’t get it appear again.
