### ISSUE TITLE
tss autocomplete adds double the quotes

### ISSUE THREAD

**Issue by Topener** [appcelerator/vscode-appcelerator-titanium#155]
### Describe the Bug
When trying to autocomplete `layout: 'horizontal'` the autocompleter will make it `layout: ''horizontal''`. 

![Screenshot 2019-11-07 at 10 41 22](https://user-images.githubusercontent.com/1898949/68378137-e25ad500-014b-11ea-890b-b90c15274d9a.png)

### Steps to reproduce the Bug

1. In a tss property, type `layout: 'ho`. 
2. Autocomplete with the `'horizontal'` option
3. It will be filled as `layout: ''horizontal''`

### Expected Behavior
Singular quotes, not double

### Your Environment
| Software | Version |
| ---------------- | ---------- |
| Titanium SDK | 8.2.1.GA |
| Appcelerator CLI | 7.1.1 |
| VS Code | 1.39.2 |
| vscode-titanium | 0.6.1 |

**Comment by ewanharris** [comment]
Thanks for the report @Topener! I think @longton95 is starting to predict issues coming in, this looks to be fixed with #153
