### ISSUE TITLE
Remove usage of workspace.rootPath

### ISSUE THREAD

**Issue by ewanharris** [appcelerator/vscode-appcelerator-titanium#157]
We currently use `workspace.rootPath` [quite a bit](https://github.com/appcelerator/vscode-appcelerator-titanium/search?q=%22workspace.rootPath%22&unscoped_q=%22workspace.rootPath%22), [it's been deprecated for some time](https://code.visualstudio.com/api/references/vscode-api#workspace.rootPath) so we really should remove that usage before it bites us. The replacement is [workspace.workspaceFolders](https://code.visualstudio.com/api/references/vscode-api#workspace.workspaceFolders), there's a bit of a difference between the two APIs so this might require some thinking

**Comment by ewanharris** [comment]
I think the best thing to do here is try and get us halfway to multi-root workspace support. When executing a command where we usually just take `workspace.rootPath` we should introduce a new prompt which looks for projects in the workspace that include a `tiapp.xml`. If there's only one we just use that, more than one then we need to prompt for the user to select.

The bits that aren't user triggered like SDK version lookup for the completions stuff I guess could be left as is for now while we figure out the right flow.

**Comment by DzzD** [comment]
Hello, maybe it could also look for timodule.xml, as it is very convenient to work on two projects : one for module and one for app that use/test this module

**Comment by ewanharris** [comment]
Closing this out as we just released 0.12.0 that includes this.

The extension now detects all valid projects in the active workspace (app or module) and will either prompt for the correct folder to run a command in (i.e. build or generate) or use the folder context in performing the actions (intellisense providers)
