### ISSUE TITLE
Use without the appc-cli

### ISSUE THREAD

**Issue by hansemannn** [appcelerator/vscode-appcelerator-titanium#30]
In development, we only use the Titanium CLI - simply because appc-cli builds are deadly slow due to the registry checks on every build. Therefore, an option to use the Titanium CLI (like the Atom plugin offers) would be great. Otherwise, it would rather be used as an editor than an IDE. Thanks!

**Comment by ewanharris** [comment]
@hansemannn, I'll be writing up the issues for this over in [the project created to track this feature](https://github.com/appcelerator/vscode-appcelerator-titanium/projects/2). As there's a few different interactions that we'll have to consider here it'll be split into a few various issues so I'm going to close this one in favour of the individual issues.
