### ISSUE TITLE
Android build prompting for certificate.

### ISSUE THREAD

**Issue by hugey010** [appcelerator/vscode-appcelerator-titanium#34]
### The Bug
When I try to run my app on Android configurations I get prompted to select a certificate with no options and no way forward.

### Steps to Reproduce
1. Create fresh appcelerator app via CLI.
```appc new -t app -n test_appc_vscode --id com.example.testappcvscode```
2. Open VSCode, wait for Titanium extension to load
3. Run app via Titanium extension in any of the ways:
   ```Ctrl+Shift+P -> Titanium Run -> Android -> Emulator | Device```
  _or_
  Titanium Explorer play button on listed targets.

### Expected Behavior
Make the build and install on emulator or device without prompting for certificate.

### Your Environment
| Software | Version |
| ---------------- | ---------- |
| Windows 10 Enterprise | 1803 |
| Titanium SDK | 7.5.0.GA |
| Appcelerator CLI | 7.0.8 |
| VS Code | 1.30.1 |
| vscode-titanium | 0.1.2 |

### Other Notes
* ```appc run -p android``` builds and runs fine.
* There are no build logs because I can't get there.

I'm happy to answer questions, help debug, and possibly make a PR if necessary. Also, thanks for making this extension!

**Comment by ewanharris** [comment]
Thanks the report @hugey010, not sure how I missed that one! I'm fixing now and will push a new version out shortly

**Comment by ewanharris** [comment]
v0.1.3 should now be live in the marketplace. Apologies for missing that!
