### ISSUE TITLE
Publish to open-vsx?

### ISSUE THREAD

**Issue by m1ga** [appcelerator/vscode-appcelerator-titanium#344]
Would it be possible to publish the extension to open-vsx.org (*Extensions for VS Code Compatible Editors*)? 

Then it would be available to e.g. VSCodium:
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace

**How to:**
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension
or
https://gist.github.com/notpushkin/7fba4e2035f2c25bb04dfb9fb51a30c5

**Comment by ewanharris** [comment]
@m1ga, I think this might be good for us to investigate. I'm out for the next week so it'll probably be a few weeks before we could look into this. If you're looking to use VS Codium today I think you could grab the vsix files we publish alongside the [release](https://github.com/appcelerator/vscode-appcelerator-titanium/releases)

**Comment by ewanharris** [comment]
@m1ga I just published the latest release to open-vsx. The page is [here](https://open-vsx.org/extension/Axway/vscode-titanium). I'll file a separate issue on jira to look at improving our CI process to automate publishing as I need to to that for the Microsoft owned marketplace also

**Comment by m1ga** [comment]
awesome! Installation worked fine (removed my local installation first ;-) ) :+1:
