### ISSUE TITLE
Asking Android SDK path continuously

### ISSUE THREAD

**Issue by nazrdogan** [appcelerator/vscode-appcelerator-titanium#35]
### Describe the Bug
Asking Android SDK path continuously

### Steps to reproduce the Bug
Steps to reproduce the behavior, e.g.:
When I try to run app  its asking me android sdk path. and I m prompting path.its working fine. but after stop the run and re-run its asking me again.
 I also set with this command
   `appc ti config android.sdk   /Users/nazirdogan/Library/Android/sdk`

<img width="669" alt="screen shot 2019-01-07 at 17 43 18" src="https://user-images.githubusercontent.com/1672303/50777257-c6747180-12a3-11e9-8fda-24a2d7d64332.png">
<img width="1010" alt="screen shot 2019-01-07 at 17 44 09" src="https://user-images.githubusercontent.com/1672303/50777347-fa4f9700-12a3-11e9-80c8-563b5221fd44.png">

### Expected Behavior
Dont ask me android path

### Your Environment
| Software | Version |
| ---------------- | ---------- |
| Titanium SDK | 7.5.0|
| Appcelerator CLI | 5.1.1 |
| VS Code | Version 1.31.0-insider (1.31.0-insider) |
| vscode-titanium | 0.13.0 |

**Comment by ewanharris** [comment]
@nazrdogan Is this happening outside of VSCode when building via the macOS terminal, or only in the integrated VSCode terminal?

For the command you're running, I believe the correct config setting is `appc ti config android.sdkPath /Users/nazirdogan/Library/Android/sdk` for setting the default Android SDK path

**Comment by nazrdogan** [comment]
@ewanharris  Terminal was also same. and after making `appc ti config android.sdkPath` problem solved. 
I found `appc ti config android.sdk` command  here. 
https://wiki.appcelerator.org/display/guides2/Installing+the+Android+SDK
you may need to update this docs
