### ISSUE TITLE
Invalid developer name when running IOS with extension

### ISSUE THREAD

**Issue by Ayyagaries** [appcelerator/vscode-appcelerator-titanium#429]
I am trying to RUN the IOS app from VS CODE and I am getting this error 

[ERROR] Invalid "--developer-name" value "Apple Development: MY NAME (TXXXXX)"

How can I fix this?

**Comment by ewanharris** [comment]
@Ayyagaries I believe you have opened a case for this via the enterprise support channels so I'm going to close this out. Please reopened if I am incorrect

**Comment by vdussan** [comment]
What was the solution to your problem?
