### ISSUE TITLE
How do you set up debugging?

### ISSUE THREAD

**Issue by Sean-Brown-Digi** [appcelerator/vscode-appcelerator-titanium#43]
To keep the issue tracker clean, we request that general questions go to the [#titanium_editors](https://ti-slack.slack.com/messages/C0FTDDNDS) channel.

I've got the extension working: it's able to build, install, and launch my app on Android. However I can't figure out how to set up a debugger in order to debug the Javascript: can someone please assist?

**Comment by ewanharris** [comment]
@Sean-Brown-Digi, hey there! We haven't investigated debugging yet, it's on the todo list at #5. I'd advise hitting the "Subscribe" button there for updates. In the meantime, you should be able to use the Chrome/Safari debuggers to debug while developing in VS Code, checkout the guides [here for iOS](https://docs.appcelerator.com/platform/latest/#!/guide/Debugging_iOS_Apps_with_3rd-party_Tools), and [here for Android](https://docs.appcelerator.com/platform/latest/#!/guide/Debugging_Android_Apps_with_3rd-party_Tools)

**Comment by Sean-Brown-Digi** [comment]
Ok thanks though I'm confused about the guide because I have the latest version of VSCode, the extension, and the appcelerator CLI, but still when I try to add the debug configuration I don't see any "Titanium" option -- is there a template of this configuration somewhere so I can just create it manually?

**Comment by ewanharris** [comment]
@Sean-Brown-Digi, we haven't released the new version of the extension yet (we close issues once the PR has been merged). I think it'll be early next week when we release, but you can follow the instructions in the PR over at #116 to download a pre-release and try it out.
