### ISSUE TITLE
Play button like Appcelerator Studio

### ISSUE THREAD

**Issue by nicolomonili** [appcelerator/vscode-appcelerator-titanium#436]
**Is your feature request related to a problem? Please describe.**
I find it a bit slow to have to press the stop button each time, and then the play button again to restart a build.
Wouldn't it be better (like the play button on Appcelerator Studio which blocks the current build with each press and automatically restarts one) to have a situation like this?

![Test1](https://user-images.githubusercontent.com/2778813/94123834-92b0f500-fe54-11ea-9441-55ce71425ffb.png)

**Describe the solution you'd like**
A play button always visible, a stop button visible only when a build is in progress. If i press the stop button, the build is stopped. If I press the play button, the build is stopped and a new one is started automatically.

**Describe alternatives you've considered**
https://github.com/appcelerator/vscode-appcelerator-titanium#commands

**Comment by ewanharris** [comment]
@nicolomonili, would you want to be prompted as to whether you want to stop the current build, or would you want it to just be done automatically?

**Comment by nicolomonili** [comment]
> @nicolomonili, would you want to be prompted as to whether you want to stop the current build, or would you want it to just be done automatically?

I think it's much better (and faster) that it all be done automatically
