### ISSUE TITLE
Android distribution procedure ask everytime same information

### ISSUE THREAD

**Issue by ottopic** [appcelerator/vscode-appcelerator-titanium#438]
**Is your feature request related to a problem? Please describe.**
Everytime I need to distribuite Android app I have to choose output location, select distribution .keystore from Finder, insert keystore Alias and password.

**Describe the solution you'd like**
This is very slowly process, all the informations should be saved in VSCode preferences.

**Comment by ewanharris** [comment]
@ottopic, we do have some [configuration options](https://github.com/appcelerator/vscode-appcelerator-titanium/blob/master/configuration.md#configuration-settings) for setting defaults for certain things (although the android settings look to be busted right now). However these are only defaults and will made available as an option in the prompting, rather then being assumed as the right value for every project.

I would recommend looking into [Tasks](https://github.com/appcelerator/vscode-appcelerator-titanium/blob/master/doc/tasks.md#using-visual-studio-code-tasks), specifically the [Package Task](https://github.com/appcelerator/vscode-appcelerator-titanium/blob/master/doc/tasks.md#titanium-package-task) to allow you to setup a reusable build definition with these properties. It doesn't allow setting the keystore password right now however

**Comment by ottopic** [comment]
@ewanharris thank you for your replay. In my configuration I already seen titanium.android.keystorePath and titanium.android.keystoreAlias, but I don't find any reference in the documentation. Should I have mandatory create a Package Task?

**Comment by ewanharris** [comment]
@ottopic, it's not required to create a Package Task, but it sounds like it fits what I think you want (set things and have them used automatically). Setting up a package task with all the required information would mean that you'll only be prompted for the keystore password when you [run that task](https://code.visualstudio.com/docs/editor/tasks#_typescript-hello-world)
