### ISSUE TITLE
Single global or custom dist path

### ISSUE THREAD

**Issue by sandrolain** [appcelerator/vscode-appcelerator-titanium#45]
Ability to specify a single global output dist path for all projects, so you can have a single directory where you can collect ipa (ad-hoc) and apk files of several different projects, or to be able to specify the dist path for the project.

**Comment by ewanharris** [comment]
Hey @sandrolain, so we do currently support this. Under the [user and workspace settings](https://code.visualstudio.com/docs/getstarted/settings), if you search for `titanium` you can see all the config options, one of which is "Distribution Output Directory". This accepts either an absolute path like `/Users/ewan/Document/app-builds` or a directory name like `app-builds`, which is created under the app project directory.

I'm not sure whether we'll add a command for setting this, but maybe (if possible) we'll add a dropdown value on the Titanium activity pane to open this settings view, and of course we'll get these config values documented in the repo too!

Could you take a look and let me know if the above solves what you're looking for?

**Comment by sandrolain** [comment]
Hello!
Sorry, I had not seen the presence of configurable parameters in the settings, this solves my need.
I do not think it is essential to add commands or controls for these parts of configuration, but certainly useful that they are documented.

Is there any way to specify different paths that are different for each project?
For example, the "dist" directory by default and only for a specific project another path?

**Comment by ewanharris** [comment]
If you open the [user and workspace settings](https://code.visualstudio.com/docs/getstarted/settings) view it should have a tab for `User Settings` and a tab for `Workspace`. Anything you set in `Workspace` will be written to a `.vscode/settings.json` file. You can set any of the config settings there so for example you could set `titanium.android.keystorePath` to the path to your keystore and have it set to the file so you don't have to pass it on every build

**Comment by sandrolain** [comment]
@ewanharris thank you so much. I should look better how VSCode works!
