### ISSUE TITLE
Distribute > Last:Android not load the last parameters

### ISSUE THREAD

**Issue by sandrolain** [appcelerator/vscode-appcelerator-titanium#47]
Distribute  => Last:Android execution not load the last parameters used after entering asked password. The path to the keystore file and the alias are "undefined".

Example:

```
appc "run" "--platform" "android" "--target" "dist-playstore" "--output-dir" "/Users/sandrolain/Documents/Titanium/MyProject/dist" "--keystore" "undefined" "--store-password" "********" "--alias" "undefined"
```

**Comment by longton95** [comment]
A new release has just been published (0.2.0) and it should now be live on the VS Code marketplace.

Thanks for the report.
