### ISSUE TITLE
Provide functionality to check/update SDKs

### ISSUE THREAD

**Issue by adamtarmstrong** [appcelerator/vscode-appcelerator-titanium#48]
Having used Appcelerator Studio for 4 years now - not having a simple GUI is the biggest gap I see that causes friction when trying to migrate from Studio to VS Code.  It was very convenient, within Studio, to simply Check and update the Titanium CLI and SDKs.

If you could provide that functionality, in some kind of GUI or pseudo-GUI, instead of using the CLI, I believe this would make the migration to VS Code a no-brainer and possibly put Appcelerator in a potion to seriously consider shutting down Studio and getting out of the business of managing your own IDE.

**Comment by ewanharris** [comment]
Hey @adamtarmstrong,

This is a really good feature request thanks for making it! I've spent some time this week speccing out how we can achieve this in VS Code. I'd love to get your feedback on this if you have some time.

We can't really emulate the Studio update dialog (a select view alongside release notes) here unfortunately as VS Code has some constraints in the types of UIs that can be built.

When opening a Titanium project in VS Code, once a day or so (timeframe not set in stone yet), we'll check in the background for updates. If there are new updates available then we'll display a dialog like in figure 1.
It'll have "Update" and "View" buttons. It will probably also outline the available updates a little better.

* Clicking "View" will open the "Update view" in the activity pane, which will outline the available updates, and link out to the release notes for each (which will open in the default browser for your system)
	* We'll add a way to open the "Update dialog" from here, or just updating a single component without going through the update dialog
* Clicking "Update" will open the "Update dialog" where the updates to be installed can be selected. These will then run in the background and we'll pop up another notification when we're finished with that.

Figure 1: Update notification
![Figure 1](https://i.imgur.com/6u40cV5.png)

Figure 2: Update view in activity pane
![Figure 2](https://i.imgur.com/MKHEfhg.png)

Figure 3: Update dialog
![Figure 3]((https://i.imgur.com/MKHEfhg.png)

cc @longton95 , @Topener for feedback too

**Comment by Topener** [comment]
Looking nice!

**Comment by adamtarmstrong** [comment]
This looks awesome!

**Comment by ewanharris** [comment]
Hey @adamtarmstrong, just to let you know we just shipped this today in 0.4.0! Thanks for the feature request!
