### ISSUE TITLE
Use debugger plugins as dependencies

### ISSUE THREAD

**Issue by hansemannn** [appcelerator/vscode-appcelerator-titanium#5]
VSCode allows developers to [specify dependencies](https://code.visualstudio.com/docs/editor/extension-gallery). We should add the following two plugins:
- iOS debugger: https://github.com/Microsoft/vscode-ios-web-debug
- Android debugger: https://github.com/Microsoft/vscode-chrome-debug

**Comment by Sean-Brown-Digi** [comment]
Can you elaborate how this extension allows someone to debug?

**Comment by ewanharris** [comment]
Closed via #116
