### ISSUE TITLE
Be open to open widget by clicking on it's identifier

### ISSUE THREAD

**Issue by hansemannn** [appcelerator/vscode-appcelerator-titanium#62]
**Is your feature request related to a problem? Please describe.**
This is a feature request. 

**Describe the solution you'd like**
It could work the same way as controllers can be opened by clicking
their identifier. Example:
```js
Alloy.createWidget('com.appc.testwidget').getView().open();
                    ^^^^^^^^^^^^^^^^^^^
                     click here to open
```

**Describe alternatives you've considered**
Open it manually :(

**Comment by ewanharris** [comment]
It's possible currently to do `Alloy.createWidget('testwidget').getView().open();` and click to open `app/widgets/testwidget/controllers/widget.js`, I guess this is just a bug with the regex where it's not handling widget names that are dotted
