### ISSUE TITLE
Titanium View (sidebar) Not Showing

### ISSUE THREAD

**Issue by ryanbuening** [appcelerator/vscode-appcelerator-titanium#639]
I installed version 0.10.1 of the Titanium extension. I'm on VS Code version 1.54.3. The Titanium view in the activity sidebar is not showing for me. Is there something else that I need to configure?

**Comment by ewanharris** [comment]
@ryanbuening the sidebar is currently only loaded if there is an open project.

If your machine is already setup for Titanium development, then you can either open an existing project in VS Code and the extension will load, or create a new one via the `Titanium: Create Application` command in the command palette.

If your machine isn't setup, I'd recommend following the getting started guide [here](https://platform.axway.com/#/product/cli) to get your machine setup for development and then review the [extension documentation](https://docs.axway.com/bundle/Titanium_SDK_allOS_en/page/visual_studio_code_extension_for_titanium.html).

Also check out the community slack [ti-slack](https://tislack.org/)

**Comment by ryanbuening** [comment]
Thanks!
