### ISSUE TITLE
Improve discoverability/usability of packaging an application

### ISSUE THREAD

**Issue by ewanharris** [appcelerator/vscode-appcelerator-titanium#642]
[ti-slack discussion](https://ti-slack.slack.com/archives/C0FTDDNDS/p1615564377005200)

### Is your feature request related to a problem? Please describe.
We want to improve the discoverability/usability of packaging applications. Currently it is only available from the Command Palette or via the icon on a platform shown in the Builder explorer.

### Describe the solution you'd like
There's a number of solutions we could provide here, most likely we will end up implementing more than one:

* Add a top level `Package` button alongside the `Run` button in the title bar of the Build Explorer
* Add a `Package` option to the three dots dropdown in the title bar of the Build Explorer
* Add a new `Package` sub-item to each platform in the Build Explorer that will list the possible distribution targets

**Comment by caspahouzer** [comment]
The main problem is, that the package button is hidden. Display it without mouseover and everything's fine 😄

**Comment by ewanharris** [comment]
@caspahouzer, yup and that's why we're looking to improve it 🙂  Thanks for the feedback!
