### ISSUE TITLE
Improve reusability of builds

### ISSUE THREAD

**Issue by ewanharris** [appcelerator/vscode-appcelerator-titanium#643]
### Is your feature request related to a problem? Please describe.
Currently, if you want to perform the same build (let's say to an iOS device) you will have to answer the same prompts repeatedly (select a cert, select a provisioning profile). 

We currently allow this to be circumvented by creating tasks, however there are two main barriers to using and consuming these:

* Task creation must be done manually
* Tasks cannot be consumed via the Build Explorer, and instead must be called via the Command Palette

Furthermore, tasks might be a step too far for most developers who simply just want to replay the same build again. We currently store the last build state, but we could extend this in certain ways by storing multiple builds and displaying them in Build Explorer

### Describe the solution you'd like
There's a few different ways we could improve this, either by focusing on improving tasks or focusing on reducing the need for tasks. Again, we could pick one or we could pick multiple.

#### Improving tasks

* Add a new command to aid in the generation of tasks that can be run via the right click menu on a device in the Build Explorer or via the Command Palette
* Display a `Tasks` sub-item alongside the platforms in the Build Explorer that shows the user-defined Titanium tasks

#### Improving build recall

* Display a `Recent` sub-item alongside the platforms in the Build Explorer that shows the most recent builds performed. We could store the last 5 builds and then display these there. (credit to @Topener for this idea)

**Comment by ewanharris** [comment]
We already offer the ability to set that information today via [tasks](https://github.com/appcelerator/vscode-appcelerator-titanium/blob/master/doc/tasks.md). The second bullet of `Improving tasks` is for adding a way to create those

Personally, I don't think this extension should be generalising and simplifying the configuration beyond tasks though as it's then getting into the realm of configuration that should maybe be performed by the CLI itself.

**Comment by caspahouzer** [comment]
Ah, didn't know that. I've got build scripts which do some more actions before the distribution build

**Comment by ewanharris** [comment]
Closing this out as we just released 0.12.0

Right click on a device (i.e simulator/emulator/device) or distribution target will now also offer a "Generate task" option, and the Build Explorer now also has a `Recent` section that shows the last 5 builds
