### ISSUE TITLE
the distribute function is broken

### ISSUE THREAD

**Issue by jason919** [appcelerator/vscode-appcelerator-titanium#70]
### Describe the Bug
this is the latest version 0.3, it was working before.
try to run "distribute" for either iOS or Android, it gave the error
Appcelerator Command-Line Interface, version 7.0.10
2019-03-31T22:17:25.554Z | ERROR  | No valid targets for run. Are you in a project folder?

I think it switched to use the standard output console instead of the terminal, then it misses the current directory info for the command line. If I copy the command to terminal, it works fine.

### Steps to reproduce the Bug
Steps to reproduce the behavior, e.g.:
1. open any project
2. Click on 'distribute'
3. See error

### Your Environment
| Software | Version |
Mac, 10.14
| Titanium SDK | |
8.0.0. GA
| Appcelerator CLI | |
7.0.10
| VS Code | |
| vscode-titanium | |
0.3

### Logs
error log
appc "run" "--platform" "ios" "--target" "dist-appstore" "--log-level" "info" "--distribution-name" "xxxxx" "--pp-uuid" "xxxxx" --no-prompt

Appcelerator Command-Line Interface, version 7.0.10
Copyright (c) 2014-2019, Appcelerator, Inc.  All Rights Reserved.

2019-03-31T22:17:25.554Z | ERROR  | No valid targets for run. Are you in a project folder?

**Comment by jason919** [comment]
I figured it out I can check the "use terminal for build", then it works like old build.

**Comment by ewanharris** [comment]
Thanks for the report @jason919, we'll hopefully have a fix out today.

**Comment by ewanharris** [comment]
v0.3.1 just shipped which fixes this
