### ISSUE TITLE
Unable to install CLI 6.0.0

### ISSUE THREAD

**Issue by dethier1958** [appcelerator/vscode-appcelerator-titanium#741]
<img width="481" alt="Failed to install" src="https://user-images.githubusercontent.com/6359232/121789874-50c10e00-cb9f-11eb-8c78-8287861d9235.png">
Issue Type: <b>Bug</b>

Tried to install latest Appcelerator CLI and it immediately fails.

Extension version: 0.12.1
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:16.617Z)
OS version: Darwin arm64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 3, 3|
|Memory (System)|16.00GB (1.88GB free)|
|Process Argv|--crash-reporter-id 52a326e9-28b1-41d7-b0b2-69f3a685aab2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by ewanharris** [comment]
Thanks for the report @dethier1958, this looks to be an issue with how we handle a failed install due to permissions. For now you should be able to install using `sudo npm i appcelerator -g` in terminal and we'll have a fix out soon

**Comment by dethier1958** [comment]
Thanks!

**Comment by ewanharris** [comment]
0.12.2 was just released with this fix, it should be rolling out shortly
