### ISSUE TITLE
provision profiles

### ISSUE THREAD

**Issue by jomollin** [appcelerator/vscode-appcelerator-titanium#813]
Issue Type: <b>Bug</b>

How can I select provision profiles. Where must they be stored

Extension version: 0.12.2
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 19, 13|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 8391f894-89ff-4b29-b0a8-90fc040f5206|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30350414

```

</details>

**Comment by ewanharris** [comment]
@jomollin, if you have some provisioning profiles on you machine you can view them using `[appc] ti info -t ios`. Make sure they match the id of your app and are valid for the certificate you're selecting.

If you don't have any installed, you need to create them on the Apple Developer site, there's some instructions [here](https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_Guide/Preparing_for_Distribution/Deploying_to_iOS_devices.html#create-and-install-a-development-provisioning-profile)

**Comment by ewanharris** [comment]
You can delete them by removing the files at `~/Library/MobileDevice/Provisioning Profiles/`. Apps built with 10.0.2 should work ok on iOS 15, but 10.1.0 will be the first release to officially support Xcode 13 and iOS 15 (https://github.com/appcelerator/titanium_mobile/pull/12873)

**Comment by jomollin** [comment]
Thanks
