### ISSUE TITLE
Prompt for Keystore Key Password

### ISSUE THREAD

**Issue by sandrolain** [appcelerator/vscode-appcelerator-titanium#84]
In some cases the keystore file for Android builds requires two different passwords for the keystore itself and the keystore key.

Currently only the first is requested, while the second is requested by the terminal to check before the build.

Is it possible to request both passwords?

Would it be possible to also save these passwords in a secure way, perhaps requesting confirmation from the user whether to save them or not?

This is usually a repetitive action and some very complex passwords are difficult to fill out. Furthermore, the password entry prompt closes when the focus is lost from Visual Studio Code, requesting to repeat the procedure from the beginning.

**Comment by ewanharris** [comment]
Thanks for the issue @sandrolain! The storage of passwords we had something on our radar there's just some complications around achieving it. I've split that request out into #89.

For the key password this is the `--key-password` flag correct? Do you think this should always be in the packaging flow (with no input meaning non value?

**Comment by ewanharris** [comment]
We added a new prompt to the flow for the keystore private key password in #92, as the securing of these passwords is split out into #89 I'm going to close this issue. We should ship the update sometime this week
