### ISSUE TITLE
ES6 functions not clickable from Alloy XML events

### ISSUE THREAD

**Issue by jasonkneen** [appcelerator/vscode-appcelerator-titanium#841]
Previously, you could declare function like ` function onClick(){}` in the controller and hold command and click the function name in the `onClick` attribute  in the XML to jump to it.

Using ES6 declarations though means this functionality doesn't work so `var onClick = ()=>{}` will not work.

**Comment by ewanharris** [comment]
Would need the `definitionRegExp` [here](https://github.com/appcelerator/vscode-appcelerator-titanium/blob/a752fd5b9829519fdc56694389310fa5922601a4/src/providers/definition/common.ts#L97) updating

**Comment by jasonkneen** [comment]
Nice work man!
