### ISSUE TITLE
Create a feature that allows user to clear the "Recent" section list.

### ISSUE THREAD

**Issue by newportsolutionsgroup** [appcelerator/vscode-appcelerator-titanium#889]
The Recent section displayed beneath the Build section of the Titanium VS Code extension displays the users recent build/run choices. Because the "Recent" section cannot be cleared by the user it can and does quickly fill up with data that is not being used frequently. 

I would like to see an icon on "Recent" section header (eraser, trash can, ?) that when clicked clears the list of recent build/run configurations performed. While prompting the user with a confirmation "Are you sure you want to clear the recent list?" would be convenient, clearing the list without confirmation first would not damage the user experience as the recent list is for convenience.

**Comment by ewanharris** [comment]
Given that you're looking to clear unused recent builds would _just_ a "clear all" work or would you also want the ability to clear each entry individually?

I thought the `Recent` view should be capped at 5 entries, is the cap of 5 builds too many?

**Comment by newportsolutionsgroup** [comment]
Agreed just a single "Clear All" button at the section header level. Five is not too many - six would be better to capture the a real test/build scenario ( 2 diff iOS sims for testing, 1 iOS build 2 diff Androids sims for testing, 1 android build )

I've clicked the wrong sim once or twice and they stay in recent list.
