### ISSUE TITLE
Tooling not working for OSS Titanium.

### ISSUE THREAD

**Issue by raybelisle** [appcelerator/vscode-appcelerator-titanium#971]
### Describe the Bug
When updating to 0.14.0 version of the VSCode extension, the Titanium tooling will not load. It shows the extension screen, asking me to install tooling.

### Steps to reproduce the Bug
Upgrade to 0.14.0, restart VSCode, click on the Titanium extension and the extension does not load.

### Expected Behavior
Extension to load.

If I reinstall the 0.13.0 the extension loads properly.

<img width="1402" alt="Screen Shot 2022-03-02 at 1 33 25 PM" src="https://user-images.githubusercontent.com/821019/156445389-49554174-5a80-4f9b-864e-c67da9ce21a9.png">

When I check the Titanum > General: Use Ti that's when I see the same behaviour. For some reason it is not finding the required files, even though they are installed? ie. I can run Ti Build with no problem. Not sure what is missing to have the extension load properly.

<img width="1400" alt="Screen Shot 2022-03-02 at 1 33 39 PM" src="https://user-images.githubusercontent.com/821019/156445804-c3ed49ed-6146-4ca3-a236-2bde10cfbb83.png">

**Comment by ewanharris** [comment]
@raybelisle if you click on `Install Tooling` what does it ask you to install? The VS Code extension [calls](https://github.com/appcelerator/vscode-appcelerator-titanium/blob/master/src/extension.ts#L73) `validateEnvironment` in [titanium-editor-commons](https://github.com/appcelerator/titanium-editor-commons/blob/master/src/environment/index.ts#L18-L91) and I think one of those checks must be failing

**Comment by jiajye78** [comment]
Hi @raybelisle , may I know what version of Ti CLI are you using? And how you perform the update?
Highly appreciate for your response =)

**Comment by raybelisle** [comment]
Make sure you upgrade the alloy and ti CLI, then it works

**Comment by jiajye78** [comment]
@raybelisle how does you perform the allow and ti cli update?
i try 'appc setup'  but its not able to find latest version

**Comment by raybelisle** [comment]
Make sure you have alloy and ti CLI up to date. Run npm i alloy -g then npm i titanium -g. As long as you have both updated to latest versions the vscode updates worked.
